#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关
mybatis:
  typeAliasesPackage: com.luyang.entity
  mapperLocations: classpath:com.luyang.mapper/*.xml
---

#开发配置
server:
  servlet:
    context-path: /abc
  uri-encoding: utf-8
  port: 8081
spring:
  profiles: dev
  datasource:
    jndi-name: jdbc/mydb
    #url: jdbc:mysql://localhost:3306/luyang?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #username: root
    #password: 123456
    #driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    password: luyang
  
  #application:
    #当前应用名称
    #name: service-hi
    
  #启动服务发现的功能，开启了才能调用其它服务 
  #cloud:
    #config:
      #discovery:
        #enabled: true
        #serviceId: compute-server
 
---    
   
a:
 b:
  c: 123456

---
#eureka:
  #client:
    #serviceUrl:
      #注册中心的地址
      #defaultZone: http://localhost:8888/eureka/  
       # 自定义实例编号
  #instance:
    #instance-id: ${spring.application.name}:${server.port}:home
    # 配置使用主机名注册服务
    #hostname: localhost
  
    
    

 
  

    
    